version: '3'
services:
  frontend:
    container_name: project_web
    build:
      context: ./client
      dockerfile: Dockerfile
    image: oskarlovsveden/project_web
    ports:
      - '3000:3000'
    volumes:
      - ./client:/usr/src/app
    stdin_open: true
  backend:
    container_name: project_server
    build:
      context: ./server
      dockerfile: Dockerfile
    image: oskarlovsveden/project_server
    ports:
      - '8000:8000'
    volumes:
      - ./server:/usr/src/app
